# .github/workflows/ci.yml
name: CI - train & test

on:
  push:
    branches: [ dev, docker_cicd, main ]

jobs:
  check_working_repo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run training
        run: |
          python train.py
      - name: Run testing
        run: |
          python test.py
